version: "3"

services:
  app:
    build:
      context: ./go
    container_name: golang_app
    depends_on:
      - mysql
    tty: true
  mysql:
    build:
      context: ./mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        container_name: golang_db
        ports:
          - "3306:3306"
        tty: true
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    image: mariadb
    ports:
      - "3306:3306"
